<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Variant-Mod-Organizer</AssemblyName>
    <Version>1.6.0</Version>
    <ApplicationIcon>Resources\Dova.ico</ApplicationIcon>
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    
    
    <DebugType>none</DebugType>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup><Resource Include="Resources/Dova.ico"/><EmbeddedResource Include="Resources\Dova-Locks_P.pak" LogicalName="Dova.Payload.pak" /></ItemGroup>
</Project>

